project:
  type: website
  pre-render:
    - uv run homepage/bin/render.sh
  render:
    - "index.qmd"
    - "gallery/*.qmd"
    - "test.qmd"
    - "!demo/"
    - "guide/"
  post-render:
    - "cp -r demo _site/"
    - "sed -e /bootstrap.*css/d -i.bak _site/index.html"

filters:
  - interlinks

execute:
  ipynb-shell-interactivity: all
  
interlinks:
  fast: true
  autolink: true
  aliases:
    plotnine: null
  sources:
    plotnine:
      url: https://plotnine.org/

format:
  html:
    theme:
      - lumen
      - styles.css
      - plotnine.scss
    toc: true
    # For proper retina (similar to what we get in the notebook),
    # double the default dpi, then using CSS maintain the default size
    fig-dpi: 200

website:
  title: Plotnine
  navbar:
    left:
      - file: guide/install.qmd
        text: "Guide"
      - text: "Reference"
        href: https://plotnine.org/reference/
      - text: "Gallery"
        href: https://plotnine.org/gallery/
      - text: "Blog"
        href: https://plotnine.org/blog.html
  sidebar:
    - title: Guide
      contents:
        - guide/install.qmd
        - guide/overview.qmd
        - section: "Basics"
          contents:
          - guide/aesthetic-mappings.qmd
          - guide/geometric-objects.qmd
          - guide/scale-basics.qmd
          - guide/position-adjustments.qmd
          - guide/facets.qmd
          - guide/coordinate-systems.qmd
        - section: "Polishing"
          contents:
          - guide/export.qmd
          - guide/labels.qmd
          - guide/annotations.qmd
        - section: "Theming"
          contents:
          - guide/themes-basics.qmd
          - guide/themes-premade.qmd
        #  - guide/themes-custom.qmd
        # - section: "Scales"
        #   contents:
        #   - guide/scale-x-and-y.qmd
        #   - guide/scale-color-fill.qmd
        #   - guide/scale-misc.qmd
        # - section: "CASE STUDIES"
        #   contents:
        #   - guide/case-study1.qmd
        #   - guide/case-study2.qmd
        #   - guide/case-study3.qmd
        - section: "Miscellaneous"
          contents:
          - guide/maps.qmd
          #- guide/shortcuts.qmd
          #- guide/misc.qmd
          #- guide/feature-coverage.qmd
          - guide/aesthetic-specification.qmd
    - id: dummy


